### ISSUE TITLE
Could you please provide trained models?

### ISSUE THREAD

**Issue by list0830** [tsa18/PCR#1]
Thank you for your excellent work on this project. It's the first work I met that implements PTQ based on diffuser library.
However, quantizing is still time-consuming. Could you kindly provide trained models of SDv1.4 and SDXL for evaluation?

**Comment by tsa18** [comment]
Thanks for your interest. Now we release the checkpoints at https://drive.google.com/drive/folders/1u9FAZ8uGNYZ1mipiFWknigqpeh9M9MnU?usp=sharing. To perform inference with them, you may need to pull the latest codes, and use the command  `python inference_sd.py --model-path  <path-to-ckpt> --save-path <path-to-save-imgs> --gpu_id 0 --batch-size 4  --path-to-test-text <path-to-test-prompt-file> --coco --seed <your-seed>`. 

We have released the quantized SD 1.4 (W8A8) checkpoint calibrated on 200 COCO prompts. Using this ckpt, you are expected to get a FID-to-FP32 score of about 8.4 and a CLIP score of about 26.47. We will upload more checkpoints later.
